/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomerReviews: typeof import('./src/components/home/CustomerReviews.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HeroSection: typeof import('./src/components/home/HeroSection.vue')['default']
    MainFooter: typeof import('./src/components/MainFooter.vue')['default']
    MainHeader: typeof import('./src/components/MainHeader.vue')['default']
    NewArrivals: typeof import('./src/components/home/NewArrivals.vue')['default']
    PrimaryButton: typeof import('./src/components/ui/PrimaryButton.vue')['default']
    ProductCard: typeof import('./src/components/ui/ProductCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StyleSection: typeof import('./src/components/home/StyleSection.vue')['default']
    TestimonyCard: typeof import('./src/components/ui/TestimonyCard.vue')['default']
    TopSelling: typeof import('./src/components/home/TopSelling.vue')['default']
  }
}
