/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/cart': RouteRecordInfo<'/cart', '/cart', Record<never, never>, Record<never, never>>,
    '/contact': RouteRecordInfo<'/contact', '/contact', Record<never, never>, Record<never, never>>,
    '/reset-password/': RouteRecordInfo<'/reset-password/', '/reset-password', Record<never, never>, Record<never, never>>,
    '/reset-password/[token]': RouteRecordInfo<'/reset-password/[token]', '/reset-password/:token', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    '/shop/': RouteRecordInfo<'/shop/', '/shop', Record<never, never>, Record<never, never>>,
    '/shop/[id]': RouteRecordInfo<'/shop/[id]', '/shop/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/signin': RouteRecordInfo<'/signin', '/signin', Record<never, never>, Record<never, never>>,
    '/signup': RouteRecordInfo<'/signup', '/signup', Record<never, never>, Record<never, never>>,
    '/user/': RouteRecordInfo<'/user/', '/user', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/about.vue': {
      routes: '/about'
      views: never
    }
    'src/pages/cart.vue': {
      routes: '/cart'
      views: never
    }
    'src/pages/contact.vue': {
      routes: '/contact'
      views: never
    }
    'src/pages/reset-password/index.vue': {
      routes: '/reset-password/'
      views: never
    }
    'src/pages/reset-password/[token].vue': {
      routes: '/reset-password/[token]'
      views: never
    }
    'src/pages/shop/index.vue': {
      routes: '/shop/'
      views: never
    }
    'src/pages/shop/[id].vue': {
      routes: '/shop/[id]'
      views: never
    }
    'src/pages/signin.vue': {
      routes: '/signin'
      views: never
    }
    'src/pages/signup.vue': {
      routes: '/signup'
      views: never
    }
    'src/pages/user/index.vue': {
      routes: '/user/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
