const products = [
  {
    id: 1,
    name: "Essential White T-Shirt",
    brand: "Urban Basics",
    category: "T-Shirts",
    price: 30,
    discount: 20,
    finalPrice: 24,
    rating: 4.5,
    reviewsCount: 132,
    inStock: true,
    image:
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?fm=png&w=800",
    description: "Clean and minimal cotton t-shirt for everyday wear.",
  },
  {
    id: 2,
    name: "Blue Denim Jacket",
    brand: "Denim Core",
    category: "Jackets",
    price: 95,
    discount: 25,
    finalPrice: 71.25,
    rating: 4.7,
    reviewsCount: 89,
    inStock: true,
    image:
      "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?fm=png&w=800",
    description: "Classic denim jacket with a modern fit.",
  },
  {
    id: 3,
    name: "Relaxed Fit Hoodie",
    brand: "Street Mode",
    category: "Hoodies",
    price: 70,
    discount: 30,
    finalPrice: 49,
    rating: 4.6,
    reviewsCount: 201,
    inStock: false,
    image:
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?fm=png&w=800",
    description: "Soft fleece hoodie designed for comfort and warmth.",
  },
  {
    id: 4,
    name: "Slim Fit Jeans",
    brand: "Denim Co",
    category: "Jeans",
    price: 65,
    discount: 15,
    finalPrice: 55.25,
    rating: 4.3,
    reviewsCount: 76,
    inStock: true,
    image:
      "https://images.unsplash.com/photo-1542272604-787c3835535d?fm=png&w=800",
    description: "Durable slim-fit jeans with stretch fabric.",
  },
  {
    id: 5,
    name: "Summer Button Shirt",
    brand: "Breeze",
    category: "Shirts",
    price: 48,
    discount: 10,
    finalPrice: 43.2,
    rating: 4.2,
    reviewsCount: 58,
    inStock: true,
    image:
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?fm=png&w=800",
    description: "Lightweight button-up shirt perfect for warm days.",
  },
  {
    id: 6,
    name: "Black Jogger Pants",
    brand: "Active Flex",
    category: "Joggers",
    price: 55,
    discount: 20,
    finalPrice: 44,
    rating: 4.5,
    reviewsCount: 119,
    inStock: true,
    image:
      "https://images.unsplash.com/photo-1593032465171-8e3dcd5b7c6b?fm=png&w=800",
    description: "Comfortable joggers suitable for training or lounging.",
  },
  {
    id: 7,
    name: "Minimal Summer Dress",
    brand: "Pure Style",
    category: "Dresses",
    price: 85,
    discount: 35,
    finalPrice: 55.25,
    rating: 4.8,
    reviewsCount: 8,
    inStock: true,
    image:
      "https://images.unsplash.com/photo-1539008835657-9e8e9680c956?fm=png&w=800",
    description: "Elegant summer dress with a clean silhouette.",
  },
  {
    id: 8,
    name: "Classic Wool Coat",
    brand: "Nordic Wear",
    category: "Coats",
    price: 150,
    discount: 40,
    finalPrice: 90,
    rating: 4.7,
    reviewsCount: 3,
    inStock: true,
    image:
      "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?fm=png&w=800",
    description: "Warm wool coat with a timeless design.",
  },
  {
    id: 9,
    name: "Cargo Utility Pants",
    brand: "Utility Lab",
    category: "Pants",
    price: 70,
    discount: 18,
    finalPrice: 57.4,
    rating: 4.4,
    reviewsCount: 2,
    inStock: true,
    image:
      "https://images.unsplash.com/photo-1583001809873-a128495da465?fm=png&w=800",
    description: "Functional cargo pants with multiple pockets.",
  },
  {
    id: 10,
    name: "Neutral Crewneck Sweater",
    brand: "Soft Knit",
    category: "Sweaters",
    price: 60,
    discount: 20,
    finalPrice: 48,
    rating: 4.6,
    reviewsCount: 9,
    inStock: true,
    image:
      "https://images.unsplash.com/photo-1600185365926-3a2ce3cdb9eb?fm=png&w=800",
    description: "Soft knit sweater ideal for cooler days.",
  },
];

export default products;
